volumes:
  db:

services:
  backend:
    stdin_open: true
    tty: true
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: dev
    command: dev
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7
    restart: unless-stopped
    expose:
      - "6379"
